//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester_Dictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class dictionary
    {
        public int id { get; set; }
        public string термин { get; set; }
        public string описание { get; set; }
        public string источник { get; set; }
    }
}
